services:
  db:
    image: postgres:16-alpine
    container_name: prp-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: prprober
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d prprober"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: prp-server
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_TYPE=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=prprober
      - DB_SSLMODE=disable
      - SERVER_PORT=:8080
      - SECRET_KEY=your_ci_secret_key
    volumes:
      - ./uploads:/app/uploads

volumes:
  postgres_data: